export const NOTES: { note: string }[] = [
  { note: "C4" },
  { note: "D4" },
  { note: "E4" },
  { note: "F4" },
  { note: "G4" },
  { note: "A4" },
  { note: "B4" },
  { note: "C5" },
  { note: "D5" },
  { note: "E5" },
  { note: "F5" },
  { note: "G5" },
  { note: "A5" },
  { note: "B5" },
  { note: "C6" },
];
